# Generated by Django 5.0.6 on 2024-11-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimValidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=20)),
                ('inicio_relacion', models.DateField()),
                ('fin_relacion', models.DateField(blank=True, null=True)),
                ('motivo_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('id_usuario', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('amid_val', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validadores.validador', to_field='amid_val')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialUbicacionesValidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_movimiento', models.IntegerField()),
                ('fecha_movimiento', models.DateField()),
                ('observacion', models.CharField(max_length=255)),
                ('id_usuario', models.IntegerField()),
                ('id_validador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validadores.validador')),
                ('ubicacion_nueva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validadores.ubicacion')),
            ],
            options={
                'unique_together': {('id_movimiento', 'id_validador')},
            },
        ),
    ]
