# Generated by Django 5.0.6 on 2024-11-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validadores', '0002_simvalidador_historialubicacionesvalidador'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialubicacionesvalidador',
            name='usuario_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historialubicacionesvalidador',
            name='usuario_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historialubicacionesvalidador',
            name='usuario_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='simvalidador',
            name='usuario_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='simvalidador',
            name='usuario_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='simvalidador',
            name='usuario_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='validador',
            name='usuario_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='validador',
            name='usuario_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='validador',
            name='usuario_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
