# Generated by Django 5.0.6 on 2024-11-06 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100)),
                ('descripcion_estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MSISDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=20, unique=True)),
                ('nodo_concert_ip', models.CharField(max_length=15)),
                ('nodo_condor_ip', models.CharField(max_length=15)),
                ('id_usuario', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SimMsisdn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=20, unique=True)),
                ('inicio_relacion', models.DateField()),
                ('fin_relacion', models.DateField(blank=True, null=True)),
                ('motivo_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('id_usuario', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim_msisdn.estadosim')),
                ('id_msisdn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim_msisdn.msisdn')),
            ],
        ),
    ]
