# Generated by Django 5.0.6 on 2024-11-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_msisdn', '0002_simmsisdn_usuario_apellido_simmsisdn_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msisdn',
            name='usuario_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='msisdn',
            name='usuario_correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='msisdn',
            name='usuario_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
