# Generated by Django 5.0.6 on 2024-11-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim_msisdn', '0003_msisdn_usuario_apellido_msisdn_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simmsisdn',
            name='id_msisdn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sim_msisdn.msisdn'),
        ),
    ]
